version: "3"


services:
  database:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  api:
    build: .
    volumes:
      - . :/SocialNetwork
    ports:
      - "2525:2525"
    command:
      - uvicorn
      - main:app
      - --host=0.0.0.0
      - --port=2525
    depends_on:
      - database
volumes:
  postgres_data:

